
BLOCK_SIZE = 500
FINAL_TERMS_SIZE = 25000
PATH = "INDEXS/"
ABS_PATH = "C:/Users/liang/PycharmProjects/comp6791p3/"

WEBSITE_CONCORDIA = 1
WEBSITE_AI = 2

RAW_PATH_CONCORDIA = "www.concordia.ca"
RAW_PATH_AI = "aitopics.org"

DATA_PATH = PATH + "DATA/"
DICT_PATH = PATH + "DICT/"
DATA = DATA_PATH + "ConcordiaAI"
DICT = DICT_PATH + "ConcordiaAI_dict_check"

DATA_PATH_AI = PATH + "DATA_AI/"
DICT_PATH_AI = PATH + "DICT_AI/"
DATA_AI = DATA_PATH_AI + "AIindex"
DICT_AI = DICT_PATH_AI + "AI_dict_check"

BLOCK_PATH_CONCORDIA = PATH + "DISK/"
MERGE_BLOCK_PATH_CONCORDIA = PATH + "MERGE_BLOCK_INDEX/"

BLOCK_PATH_AI = PATH + "DISK_AI/"
MERGE_BLOCK_PATH_AI = PATH + "MERGE_BLOCK_INDEX_AI/"

AI_DF = PATH + "AI_df.txt"

TOKEN_NUMBER_PATH = PATH + "TOKEN_NUMBER/"
TOKEN_NUMBER_CONCORDIA = TOKEN_NUMBER_PATH + "tokens_number.txt"
TOKEN_NUMBER_AI = TOKEN_NUMBER_PATH + "tokens_number_ai.txt"


REQUIRMENT_PATH = PATH + "REQUIRMENT/"
REQUIRMENT_CONCORDIA_INDEX = REQUIRMENT_PATH + "ConcordiaAI"
REQUIRMENT_AI_INDEX = REQUIRMENT_PATH + "AIindex"

QUERY_AND = "and"
QUERY_OR = "or"
QUERY_SINGLE = "single"
QUERY_BM25 = "bm25"
QUERY_TFIDF = "tfidf"

EXIT = "exit"